### PR TITLE
Introduce PSR-4

### LINKED ISSUE #7: Separate declarations from side-effects
1. move the main class to lib/Underpin.php
1. move underpin() to lib/helpers.php
1. autoload wordpress-autoloader.php and lib/helpers.php with Composer
1. Provide an example of loading Underpin - see below
1. remove autoloading from abstracts\Underpin

```php
require_once __DIR_ . '/vendor/autoload.php';

add_action( 'plugins_loaded', '\\Underpin\\underpin' );
```

### PR DESCRIPTION
**Pull request by szepeviktor**
Closes #7 

I do not understand

- Should WordPress be managed by Composer? So /vendor lives [above core](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/WordPress.md#semisecret-subdirectory-structure) or inside theme or inside Underpin?
- Is Underpin technically a WP plugin (/wp-content/plugins/) or a library (/vendor/)?

I've put a line into README about starting Underpin.

### CODE REVIEW

**Comment by szepeviktor** [comment]
💡 I leave this all up to You as I'm not a developer, so I don't use Underpin.

**Comment by szepeviktor** [comment]
Now :) it is possible to find bugs in Underpin!

See https://github.com/alexstandiford/underpin/issues/7#issuecomment-701166142

**Comment by alexstandiford** [comment]
This was painful, but I managed to get everything moved into using PSR-4 standards across Underpin and all core loaders. Thanks for opening this @szepeviktor

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request closed without merging**
